sudo: required
services:
  - docker

before_install:
  - docker build -t cczhuang/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cczhuang/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: <your s3 bucket name>
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
